### ISSUE TITLE
[REQUEST] Add option to parse only robots.txt files

### ISSUE THREAD

**Issue by mr0xE** [signedsecurity/sigurlfind3r#1]
Really quick tool, it would be great if it parses only *robots.txt* file

**Comment by enenumxela** [comment]
@mr0xE I intended for the tool to be passive

**Comment by mr0xE** [comment]
Add option to blacklist certain file types e.g png,ico,jpg,css

**Comment by enenumxela** [comment]
Great suggestion, I will work on it

**Comment by enenumxela** [comment]
> Add option to blacklist certain file types e.g png,ico,jpg,css

@mr0xE , I added a `-f, --filter` option
