### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by emil246** [signedsecurity/sigurlfind3r#11]
**Describe the bug**
panic: runtime error: index out of range [0] with length 0

**Steps To Reproduce**
./sigurlfind3r -d example.com -iS
**Output**
[ INF ] fetching urls for

panic: runtime error: index out of range [0] with length 0

goroutine 18 [running]:
github.com/signedsecurity/sigurlfind3r/pkg/sigurlfind3r/scraping/sources/commoncrawl.(*Source).Run.func1()
	/Users/emilaltynbaev/Documents/bugbounty/tools/sigurlfind3r/pkg/sigurlfind3r/scraping/sources/commoncrawl/commoncrawl.go:82 +0x7bc
created by github.com/signedsecurity/sigurlfind3r/pkg/sigurlfind3r/scraping/sources/commoncrawl.(*Source).Run
	/Users/emilaltynbaev/Documents/bugbounty/tools/sigurlfind3r/pkg/sigurlfind3r/scraping/sources/commoncrawl/commoncrawl.go:63 +0xf2

**Additional context**
MacOS 12.1

**Comment by enenumxela** [comment]
Fixed in version v1.6.1
