### ISSUE TITLE
Output save in File

### ISSUE THREAD

**Issue by awais922609** [signedsecurity/sigurlfind3r#4]
Hello , Really great tool but I noticed that there is no option for saving output in a file that causes a lot of problem for me. It would be really really best if you kindly add this feature to this tool for saving output in a file.

**Comment by enenumxela** [comment]
Great, I will add the option. For the time being perhaps you could pipe the results to a file like `sigurlfind3r -d [DOMAIN] --silent > urls.txt`

**Comment by Elsfa7-110** [comment]
also you can make it easily by
 | anew -q xxx.txt
and use -s to output urls only
